/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Face Up Task API
 * API documentation for Face Up Task
 * OpenAPI spec version: 1.0.0
 */

export * from './getApiInstitutionsId404';
export * from './getApiReports200';
export * from './getApiReportsParams';
export * from './institution';
export * from './postApiReportsBody';
export * from './report';
export * from './reportFile';
export * from './reportInstitution';