/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Face Up Task API
 * API documentation for Face Up Task
 * OpenAPI spec version: 1.0.0
 */

export interface Institution {
  createdAt?: string;
  id?: string;
  name?: string;
  updatedAt?: string;
}
