/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Face Up Task API
 * API documentation for Face Up Task
 * OpenAPI spec version: 1.0.0
 */
import type { NotificationFile } from './notificationFile';

export interface Notification {
  createdAt?: string;
  files?: NotificationFile[];
  id?: string;
  message?: string;
  updatedAt?: string;
  userId?: string;
}
