/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Face Up Task API
 * API documentation for Face Up Task
 * OpenAPI spec version: 1.0.0
 */

export type PostApiReportsBody = {
  /** Files to attach to the report */
  files?: Blob[];
  /** ID of the institution */
  institutionId: string;
  /** Content of the report */
  message: string;
  /**
   * Age of the sender
   * @minimum 1
   * @maximum 150
   */
  senderAge: number;
  /** Name of the sender */
  senderName: string;
};
